#!/bin/bash
repo="612-2013"
echo "what is your username"
read username
echo "what is your github email address"
read email
echo "Go to Github and fork Anirudh's repository for this year called"
echo $repo
echo "press enter to continue"
read -s continue
echo "is git installed [y] [n]"
read installed
if [ $installed == n ] ; then
    echo "please install git and press enter to continue"
    read $continue
fi

Depend()
{
    sudo add-apt-repository ppa:ubuntu-wine/ppa
    sudo apt-get update
    sudo apt-get install wine1.5
    wget "http://sourceforge.net/projects/wput/files/wput/0.6/wput_0.6-1_i386.deb/download?use_mirror=hivelocity&download=" -O wput.deb
    sudo dpkg -i wput.deb
    sudo apt-get install python2
    wget http://sourceforge.net/projects/tcl/files/Tcl/8.4.20/tcl8.4.20-src.tar.gz/download?use_mirror=hivelocity -0 tcl.tar.gz
    tar -x tcl.tar.gz
    git clone git@github:jkbr/httpie
    cd httpie
    ./configure
    sudo make
    sudo make install
}
GitConfig()
{
    echo "what is your name"
    read $name
    git config --global user.name $name
    git config --global user.email "$email"
}
GitRepo()
{
    git clone git@github.com:$username/$repo
    #echo "1"
    cd $repo
    #echo "2"
    git remote add upstream git://github.com/anidev/$repo.git
    #echo "3"
    git pull upstream master
#echo "4"
}
UCPP()
{
    echo "Is this Ubuntu or a debian-based OS (uses apt-get) [y] [n]"
    read Ubuntu
    if [ $Ubuntu == "n" ] ; then
    exit
    fi
    WINE
    git clone git@github.com:anidev/ucpp
    echo "1"
    sudo echo "\"export PATH=\"$PATH:~/robotics/ucpp/ucpp" >> ~/.bashrc
    echo "2"
    ucpp setup -t 612
    echo "3"
    ucpp init
    echo "4"
    ucpp configure
    echo "5"
}

#SSH
#GitConfig
#GitRepo
UCPP
